name: Android Build

on: [push]

jobs:
  build:
    name: "Linux build"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Give permission to 'gradlew'
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
