name: Android Build

on: [push]

jobs:
  build:
    name: "Linux build"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Give permission to 'gradlew'
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload lint results
      uses: actions/upload-artifact@v1
      with:
        name: Lint Results.html
        path: app/build/reports/lint-results.html
    - name: Check existance
      run: cat | ls app/build/outputs/apk/release
